spring:
  application:
    name: social
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:social;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
server:
  port: 7070
jwt:
  token:
    header: api_key
    issuer: social
    clientSecret: bXl1bmdqaW4=
    expirySeconds: 6000
cloud:
  aws:
    s3:
      region: ap-northeast-2
      accessKey: ACCESS_KEY
      secretKey: SECRET_KEY
      url: https://s3.ap-northeast-2.amazonaws.com
      bucketName: myungjin-social
